[project]
name = "hh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "blessed>=1.20.0",
    "pre-commit>=4.1.0",
    "ruff>=0.9.3",
    "yfinance>=0.2.52",
]
